#!/bin/sh

# Super-down

source /home/tim/scripts/TF/init

if [ $WX -eq $(((SW-WW)/2)) -a $WY -eq $(((SH-WH)/2)) -a $WW -eq 1024 -a $WH -eq 768 ]; then
    exit  # Do nothing if already in desired state
elif [  $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $(((SH/2)-OFFSET_HALF_BAR_BORDER)) -a $WY -eq $OFFSET_BAR ]; then # If quarter up
    wtp $WX $(((SH/2)+OFFSET_HALF_BAR)) $WW $WH $WID                                                                   # Make quarter down
elif [ $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $((SH-OFFSET_BAR_BORDER)) ]; then                                  # If half
    wtp $WX $(((SH/2)+OFFSET_HALF_BAR)) $WW $(((SH/2)-OFFSET_HALF_BAR_BORDER)) $WID                                    # Make quarter down
else
    wtp $(((SW-WW)/2)) $(((SH-WH)/2)) 1024 768 $WID                                                                    # Center and resize
fi
