#!/bin/sh

# Super-Left

source /home/tim/scripts/TF/init


if [ $WX -eq 0 -a $WY -eq $OFFSET_BAR -a $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $((SH-OFFSET_BAR_BORDER)) ]; then
    exit  # Do nothing if desired state already reached
elif [ $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $(((SH/2)-OFFSET_HALF_BAR_BORDER)) -a $WX -eq $((SW/2)) ]; then # If quarter right
    wtp 0 $WY $WW $WH $WID                                                                                          # Make quarter left
else
    wtp 0 $OFFSET_BAR $(((SW/2)-OFFSET_BORDER)) $((SH-OFFSET_BAR_BORDER)) $WID                                      # move half left
fi
