#!/bin/sh

# Super-Left

WID=$(pfw)
WW=$(wattr w $WID)
WH=$(wattr h $WID)
WX=$(wattr x $WID)
WY=$(wattr y $WID)

ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

if [ $WH -eq $((SH/2)) -a $WW -eq $((SW/2)) -a $WX -eq $((SW/2)) ]; then  # quarter right
    wtp 0 $WY $WW $WH $WID                                                # move quarter left
else
    wtp 0 0 $((SW/2)) $SH $WID                                            # move half left
fi
