#!/bin/sh

# Super-right

OFFSET_BAR=19
OFFSET_HALF_BAR=10
OFFSET_BORDER=6
OFFSET_BAR_BORDER=25
OFFSET_HALF_BAR_BORDER=16

WID=$(pfw)
WW=$(wattr w $WID)
WH=$(wattr h $WID)
WX=$(wattr x $WID)
WY=$(wattr y $WID)

AM=$(pfm)
SW=$(mattr w $AM)
SH=$(mattr h $AM)

if [ $WX -eq $((SW/2)) -a $WY -eq $OFFSET_BAR -a $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $((SH-OFFSET_BAR_BORDER)) ]; then
    exit  # Do nothing if desired state already reached
elif [ $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $(((SH/2)-OFFSET_HALF_BAR_BORDER)) -a $WX -eq 0 ]; then # If quarter left
    wtp $((SW/2)) $WY $WW $WH $WID                                                                          # Make quarter right
else
    wtp $((SW/2)) $OFFSET_BAR $(((SW/2)-OFFSET_BORDER)) $((SH-OFFSET_BAR_BORDER)) $WID                      # move half right
fi
