#!/bin/sh

# Super-right

source /home/tim/scripts/TF/init

if [ $WX -eq $((SW/2)) -a $WY -eq $OFFSET_BAR -a $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $((SH-OFFSET_BAR_BORDER)) ]; then
    exit  # Do nothing if desired state already reached
elif [ $WW -eq $(((SW/2)-OFFSET_BORDER)) -a $WH -eq $(((SH/2)-OFFSET_HALF_BAR_BORDER)) -a $WX -eq 0 ]; then # If quarter left
    wtp $((SW/2)) $WY $WW $WH $WID                                                                          # Make quarter right
else
    wtp $((SW/2)) $OFFSET_BAR $(((SW/2)-OFFSET_BORDER)) $((SH-OFFSET_BAR_BORDER)) $WID                      # move half right
fi
